- 4/Dockerfile.rhel7
- 4/s2i/bin/usage
Fix usage and remove beta name from LABEL
Signed-off-by: Petr Kubat <pkubat@redhat.com>
> Use OSE-3.2 repo for nss_wrapper

- 4/Dockerfile.rhel7
Labels now should follow spec at https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md
> New labels for OSBS

- 4/Dockerfile
- 4/Dockerfile.rhel7
- 4/root/opt/app-root/etc/generate_container_user
- README.md
Use maintainer label consistently
Few edits in top-level README
Using usage label and command
Remove hard-coded /opt/app-root in Dockerfile
Update common submodule content
> Various small documentation related changes

- specs/multispec.yml
> Use F28 as base and don't use candidate-registry for Fedora images

- src/macros.tpl
> Update labels - Fedora was missing com.redhat.component

- specs/multispec.yml
- src/macros.tpl
- src/s2i/bin/run
- src/s2i/bin/usage
also move rhel8 varnish-6 image to ubi8/s2i-core
> add distro specific branches to s2i scripts

- src/Dockerfile.template
- src/macros.tpl
add varnish-modules
modify Dockerfile.template to accomodate version specific install changes
> Add modifications from rhscl 3.3

- test/run
This commit adds function to run all
tests and report results at the end.
> Add run_all_tests function

- specs/multispec.yml
> Multispec file is wrong. image_name should not contain Quay.io

- imagestreams/varnish-centos.json
- imagestreams/varnish-rhel.json
> Depretace imagestream 5 for RHEL7 and CentOS7

- .github/workflows/build-and-push.yml
- .github/workflows/centos7-openshift-tests.yaml
- .github/workflows/centos7-tests.yaml
- .github/workflows/fedora-tests.yaml
- .github/workflows/rhel7-openshift-tests.yaml
- .github/workflows/rhel7-openshift4-tests.yaml
- .github/workflows/rhel7-tests.yaml
- .github/workflows/rhel8-tests.yaml
> Add support for GitHub Actions

- .github/workflows/build-and-push.yml
> Fetch all git sources and switch to generated

- .github/workflows/build-and-push.yml
> Generated source by dist-gen in build-and-push.yml

- .github/workflows/container-tests.yml
> Add support for testing C8s by Github Action

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
> Use RHEL-8-Updated

- 6/Dockerfile.rhel9
- 6/README.md
- README.md
- manifest.sh
- specs/multispec.yml
- src/Dockerfile.template
- src/README.md
This pull request adds support for building and testing varnish-6 container on RHEL9 host.
It also updates documentation with proper references.
> Support building and testing varnish 6 container on RHEL9 host

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
> Let's use released RHEL-9

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
This pull request allows testing single version by container and openshift tests.
> Support single versions

- .github/workflows/build-and-push.yml
- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
This pull request adds support for building, testing, and pushing varnish-7
> Add support building, testing, and pushing varnish-7

- 6/s2i/bin/usage
- 7/s2i/bin/usage
- src/s2i/bin/usage
> Replace docker with podman in s2i usage

- .github/workflows/auto-merge-on-demand.yml
- .github/workflows/auto-merge.yml
- .github/workflows/container-tests.yml
- .github/workflows/pr-metadata.yml
> Enable testing on RHEL10
