sclorg/varnish-container

- hack/build.sh
This PR fixes problem when version in openshift namespace  is not the lesser one (example of s2i-python-container). In this case, `NAMESPACE` variable is not set back to `openshift/` and created versions have wrong name.
@hhorak @bparees Same as sclorg/s2i-python-container#148. Please merge.
> Fix getting container names of versions in openshift namespace

- 4/cccp.yml
This is for the purpose of building these containers
on the CentOS Container pipeline.
> Added cccp.yml to the centos container pipeline.

- 4/test/run
This may lead to conflicts with tests for different repository.
@hhorak Please take a look.
> Do not publish a container's port(s) to the host in tests

- 4/Dockerfile
For centos/ namespaced images use centos/ namespaced s2i base image. This image is based on https://github.com/sclorg/s2i-base-container/ and is built by coreservices-jenkins maintained by RHSCL team.
@hhorak @bparees Please take a look and merge.
> Use centos/ namespaced s2i base image

- 4/test/run
Similarily to: sclorg/s2i-python-container#229
> tests: replace removed s2i flag

- .gitignore
- 4/Dockerfile
- 4/Dockerfile.rhel7
FIX:
Enable `devtoolset-4` SCL by default - `rh-varnish4-varnish` requires gcc and it is provided by `devtoolset-4-gcc`.
Also update build scripts.
@pkubatrh @hhorak Please take a look and if it is fine merge.
> Missing gcc -> tests fail

- src/s2i/bin/assemble
Adds fix-permissions right after cp and add -a to cp command.
Reference issue:
https://github.com/sclorg/container-common-scripts/issues/119
> Fix permissions for all files given in s2i

- imagestreams/varnish-centos7.json
- imagestreams/varnish-rhel7-ppc64le.json
- imagestreams/varnish-rhel7-s390x.json
- imagestreams/varnish-rhel7.json
The imagestreams were created based on ngixn, but they are not tested so far, so we should not merge it yet.
> Add image streams for CentOS 7 and RHEL 7

- specs/multispec.yml
This PR fixes Fedora builds.
Fedora container is not built for version 5. Varnish 6 is available since Fedora 30.
> Fix fedora build

- test/imagestreams
- test/run-openshift-local-cluster
- test/run-openshift-remote-cluster
- test/test-lib-varnish.sh
This PR combines more changes:
- add image stream test
- adopts new functions refactored in https://github.com/sclorg/container-common-scripts/pull/155/files
- enables tests to be run in a remote OCP4 cluster
> Use refactored functions and enable testing in remote OCP4

- README.md
- specs/multispec.yml
- src/Dockerfile.template
- src/README.md
This commit adds support for Quay.io registry instead of Docker.io.
The reason for this is the rate limit introduced by Docker.io.
> Support quay io

- test/run-openshift-remote-cluster
- test/test-lib-remote-openshift.sh
- test/test-lib-varnish.sh
This pull request adds the possibility to test varnish-container under OpenShift 4 environment.
For easy testing, just write down into the comment `[test-openshift-4]`
> Support varnish container under OpenShift 4

- Makefile
- specs/multispec.yml
- src/README.md
> Deprecate Varnish 5 which reached EOL in May 2021

- .github/workflows/docker-tests.yml
This pull request adds support for testing `varnish-container` on CentOS Stream 9.
> Add support for testing varnish-container on C9S

- .github/workflows/build-and-push.yml
- 6/Dockerfile.c9s
This pull request adds support for building, testing and pushing container `varnish-6` for CentOS Stream 9.
What is changed in Dockerfile.c9s?
See diff:
```bash
$ diff 6/Dockerfile.rhel8 6/Dockerfile.c9s
1c1
< FROM ubi8/s2i-core:1
---
> FROM quay.io/sclorg/s2i-core-c9s:c9s
23,24c23,24
<       usage="s2i build https://github.com/sclorg/varnish-container.git --context-dir=6/test/test-app/ rhel8/varnish-6 sample-server" \
<       name="rhel8/varnish-6" \
---
>       usage="s2i build https://github.com/sclorg/varnish-container.git --context-dir=6/test/test-app/ quay.io/sclorg/varnish-6-c9s sample-server" \
>       name="sclorg/varnish-6-c9s" \
28d27
<     yum -y module enable varnish:6  && \
```
> Support testing, building and pushing container for C9S

- .github/workflows/build-and-push.yml
- 6/Dockerfile
- 6/Dockerfile.c8s
- 6/Dockerfile.rhel7
- 6/README.md
- README.md
- manifest.sh
- specs/multispec.yml
- src/Dockerfile.template
- src/README.md
- src/macros.tpl
This pull request adds support for testing, building, and pushing varnish-container in CentOS Stream 8.
It also updates documentation.
Difference between Dockerfile.rhel8 and Dockerfile.c8s:
```bash
diff 6/Dockerfile.rhel8 6/Dockerfile.c8s
1c1
< FROM ubi8/s2i-core:1
---
> FROM quay.io/sclorg/s2i-base-c8s:c8s
20,21d19
<       com.redhat.component="varnish-6-container" \
<       com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#rhel" \
23,24c21,22
<       usage="s2i build https://github.com/sclorg/varnish-container.git --context-dir=6/test/test-app/ rhel8/varnish-6 sample-server" \
<       name="rhel8/varnish-6" \
---
>       usage="s2i build https://github.com/sclorg/varnish-container.git --context-dir=6/test/test-app/ sclorg/varnish-6-c8s …
```
> Support testing pushing c8s

- test/run-openshift-remote-cluster
Nowadays, we use the external OpenShift registry for the testing image.
OpenShift 4 provides an internal OpenShift registry. Let's use it.
> Use internal openshift registry

- test/run-openshift-remote-cluster
- test/test-lib-varnish.sh
- test/test-openshift.yaml
This pull request allows testing varnish-container in CVP pipeline.
The changes are:
* `common` directory is updated to the latest
* added link `test-openshift.yaml` from `common` directory
* added support for testing imagestreams on rhel8 in `test-lib-varnish.sh` file
* added support for tagging varnish image for CVP `run-openshift-remote-cluster`
> Support cvp

- test/run
Partially solves: https://github.com/sclorg/varnish-container/issues/111
> container tests: the tests should be run with the 'u' bash option

- .github/workflows/container-tests.yml
- .github/workflows/openshift-tests.yml
It will be ran with the pull request tests. It will fail the testsuite before running actual tests if the content was not regenerated properly in the PR.
> add distgen check to CI tests

- 6/Dockerfile.c8s
- 6/Dockerfile.c9s
- 6/Dockerfile.rhel7
- 6/Dockerfile.rhel8
- 6/Dockerfile.rhel9
- 7/Dockerfile.fedora
- src/Dockerfile.template
Add a test in Dockerfile directly to check varnish version
Otherwise when a wrong stream is installed, it's only found by scl test, which is too late in the process.
> Add a test in Dockerfile directly to check varnish version

- 6/s2i/bin/assemble
- 7/s2i/bin/assemble
- src/s2i/bin/assemble
This pull request change assemble script so that sources are moved and not copied
as it is done in s2i-php-container or s2i-python-container 
See: https://github.com/sclorg/s2i-python-container/blob/master/src/s2i/bin/assemble#L62
Closes: #42
> This pull request fixes issue 42

- 6/Dockerfile.c9s
- 6/Dockerfile.rhel8
- 6/Dockerfile.rhel9
- 7/Dockerfile.c10s
- 7/Dockerfile.fedora
- specs/multispec.yml
This pull request replaces nss_wrapper with nss_wrapper-libs
Less dependency and unnecessary footprint
> replaces nss_wrapper with nss_wrapper-libs

- .github/auto-merge.yml
- 6/README.md
- 7/Dockerfile.rhel10
- 7/README.md
- README.md
- manifest.yml
- specs/multispec.yml
- src/Dockerfile.template
- src/README.md
The first commit adds sources for RHEL10
THe second commit adds generated files
> Building testing rhel10

- 6/Dockerfile.rhel9
- specs/multispec.yml
Rename package bind-utils to bind9.18-utils
See Jira Ticket: https://issues.redhat.com/browse/RHEL-80345
> Rename package bind-utils to bind9.18-utils
